apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: mrhawker/bonvoyage.auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: true
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}